export enum Category {
  RetraitRappelSpecifique = 'RetraitRappelSpecifique',
  Coronavirus = 'Coronavirus',
  CafeRestaurant = 'CafeRestaurant',
  AchatMagasinInternet = 'AchatMagasinInternet',
  AchatMagasin = 'AchatMagasin',
  AchatInternet = 'AchatInternet',
  ServicesAuxParticuliers = 'ServicesAuxParticuliers',
  EauGazElectricite = 'EauGazElectricite',
  TelephonieFaiMedias = 'TelephonieFaiMedias',
  BanqueAssuranceMutuelle = 'BanqueAssuranceMutuelle',
  IntoxicationAlimentaire = 'IntoxicationAlimentaire',
  Internet = 'Internet',
  TravauxRenovations = 'TravauxRenovations',
  VoyageLoisirs = 'VoyageLoisirs',
  Immobilier = 'Immobilier',
  Sante = 'Sante',
  Animaux = 'Animaux',
  DemarchesAdministratives = 'DemarchesAdministratives',
  VoitureVehiculeVelo = 'VoitureVehiculeVelo',
  DemarchageAbusif = 'DemarchageAbusif',
}
