export const activityCodes: { [key: string]: string } = {
  '10': 'Industries alimentaires',
  '11': 'Fabrication de boissons',
  '12': 'Cultures permanentes',
  '13': 'Fabrication de textiles',
  '14': 'Production animale',
  '15': 'Industrie du cuir et de la chaussure',
  '16': 'Act. soutien agr. & trait. prim. récolt.',
  '17': 'Chasse, piégeage et services annexes',
  '18': "Imprimerie & reprod. d'enregistrements",
  '19': 'Cokéfaction et raffinage',
  '20': 'Industrie chimique',
  '21': 'Sylviculture & autres act. forestières',
  '22': 'Fab. prod. en caoutchouc & en plastique',
  '23': 'Fab. aut. prod. minéraux non métalliques',
  '24': "Services de soutien à l'expl. forestière",
  '25': 'Fab. prod. métalliq. sf machine & équipt',
  '26': 'Fab. prod. informat., électroniq. & opt.',
  '27': "Fabrication d'équipements électriques",
  '28': 'Fabric. de machines & équipements n.c.a.',
  '29': 'Industrie automobile',
  '30': "Fabric. d'autres matériels de transport",
  '31': 'Pêche',
  '32': 'Aquaculture',
  '33': 'Réparation & install. machine & équipt',
  '35': 'Prdn & distr. élec. gaz vap. & air cond.',
  '36': "Captage, traitement & distribution d'eau",
  '37': 'Collecte et traitement des eaux usées',
  '38': 'Collecte, gestion déchets ; récupération',
  '39': 'Dépollution & autre sces gestion déchets',
  '41': 'Construction de bâtiments',
  '42': 'Génie civil',
  '43': 'Travaux de construction spécialisés',
  '45': 'Commerce & répar. automobile & motocycle',
  '46': 'Commerce gros hors auto. & motocycle',
  '47': 'Com. détail, sf automobiles & motocycles',
  '49': 'Transport terrest. & trans. par conduite',
  '50': 'Transports par eau',
  '51': 'Extraction de houille',
  '52': 'Extraction de lignite',
  '53': 'Activités de poste et de courrier',
  '55': 'Hébergement',
  '56': 'Restauration',
  '58': 'Édition',
  '59': 'Prod. films ; enr. sonore & éd. musicale',
  '60': 'Programmation et diffusion',
  '61': 'Télécommunications',
  '62': 'Pgmtion conseil & aut. act. informatique',
  '63': "Services d'information",
  '64': 'Act. financ. hs assur. & cais. retraite',
  '65': 'Assurance',
  '66': "Act. auxiliaire sces financ. & d'assur.",
  '68': 'Activités immobilières',
  '69': 'Activités juridiques et comptables',
  '70': 'Act. sièges sociaux ; conseil de gestion',
  '71': 'Extraction de minerais de fer',
  '72': 'Recherche-développement scientifique',
  '73': 'Publicité et études de marché',
  '74': 'Aut. act. spécial. scientifique & techn.',
  '75': 'Activités vétérinaires',
  '77': 'Activités de location et location-bail',
  '78': "Activités liées à l'emploi",
  '79': 'Act .ag. voyage voyagiste sv. résa. etc.',
  '80': 'Enquêtes et sécurité',
  '81': 'Sces relatifs bâtimnt & aménagt paysager',
  '82': 'Act. admin. & aut. act. soutien aux ent.',
  '84': 'Admin. publi. & défense; séc. soc. obli.',
  '85': 'Enseignement',
  '86': 'Activités pour la santé humaine',
  '87': 'Hébergement médico-social et social',
  '88': 'Action sociale sans hébergement',
  '89': 'Activités extractives n.c.a.',
  '90': 'Act. créativ. artistiques & de spectacle',
  '91': "Act. de soutien à l'extr. hydrocarbures",
  '92': "Organisation jeux de hasard & d'argent",
  '93': 'Act. sportiv., récréatives & de loisirs',
  '94': 'Activités des organisations associatives',
  '95': 'Répar. ordi. & bien perso. & domestique',
  '96': 'Autres services personnels',
  '97': 'Act. ménage: empl. de person. domestique',
  '98': 'Act. ménage : prod. b.&s. (usage propre)',
  '99': 'Act. de soutien aut. indus. extractives',
  '10.1': 'Transf. & conserv. viande & prép. viande',
  '10.2': 'Transf. & conserv. poisson, crust., etc.',
  '10.3': 'Transf. et conserv. de fruits et légumes',
  '10.4': 'Fab. huile et graisse végétale & animale',
  '10.5': 'Fabrication de produits laitiers',
  '10.6': 'Travail des grains ; fab. prod. amylacé',
  '10.7': 'Fab. prod. boulangerie-pâtis. & pâtes',
  '10.8': "Fabric. d'autres produits alimentaires",
  '10.9': "Fabrication d'aliments pour animaux",
  '11.0': 'Fabrication de boissons',
  '11.1': 'Cult céréale, légumineuse, graine oléag.',
  '11.2': 'Culture du riz',
  '11.3': 'Cult. légume, melon, racine & tubercule',
  '11.4': 'Culture de la canne à sucre',
  '11.5': 'Culture du tabac',
  '11.6': 'Culture de plantes à fibres',
  '11.9': 'Autres cultures non permanentes',
  '12.0': 'Fabrication de produits à base de tabac',
  '12.1': 'Culture de la vigne',
  '12.2': 'Culture fruits tropicaux et subtropicaux',
  '12.3': "Culture d'agrumes",
  '12.4': 'Culture de fruits à pépins et à noyau',
  '12.5': "Cult. d'aut. fruits & de fruits à coque",
  '12.6': 'Culture de fruits oléagineux',
  '12.7': 'Culture de plantes à boissons',
  '12.8': 'Cult. plante aromatiq. médicin. pharma.',
  '12.9': 'Autres cultures permanentes',
  '13.0': 'Reproduction de plantes',
  '13.1': 'Prépa. de fibres textiles et filature',
  '13.2': 'Tissage',
  '13.3': 'Ennoblissement textile',
  '13.9': "Fabrication d'autres textiles",
  '14.1': "Fab. de vêtements, autres qu'en fourrure",
  '14.2': "Élevage d'autres bovins et de buffles",
  '14.3': "Élevage de chevaux et d'autres équidés",
  '14.4': "Élevage de chameaux & d'autres camélidés",
  '14.5': "Élevage d'ovins et de caprins",
  '14.6': 'Élevage de porcins',
  '14.7': 'Élevage de volailles',
  '14.9': "Élevage d'autres animaux",
  '15.0': 'Culture et élevage associés',
  '15.1': 'Indust. cuir & fourrure; maroq. & selle.',
  '15.2': 'Fabrication de chaussures',
  '16.1': 'Activités de soutien aux cultures',
  '16.2': 'Fab. article bois, liège, vannerie, etc.',
  '16.3': 'Traitement primaire des récoltes',
  '16.4': 'Traitement des semences',
  '17.0': 'Chasse, piégeage et services annexes',
  '17.1': 'Fab. de pâte à papier, papier et carton',
  '17.2': "Fab. d'articles en papier ou en carton",
  '18.1': 'Imprimerie et services annexes',
  '18.2': "Reproduction d'enregistrements",
  '19.1': 'Cokéfaction',
  '19.2': 'Raffinage du pétrole',
  '20.1': 'Fab. prod. chimi., plast. & caout. synt.',
  '20.2': 'Fab. pesticide & aut. prod. agrochimique',
  '20.3': 'Fab. de peinture, vernis, encre & mastic',
  '20.4': 'Fab. savon, prod. entretien & parfum',
  '20.5': "Fabrication d'autres produits chimiques",
  '20.6': 'Fab.  fibre artificielle ou synthétique',
  '21.0': 'Sylviculture & autres act. forestières',
  '21.1': 'Fab. de produits pharmaceutiques de base',
  '21.2': 'Fabric. de préparations pharmaceutiques',
  '22.0': 'Exploitation forestière',
  '22.1': 'Fabrication de produits en caoutchouc',
  '22.2': 'Fabrication  de produits en plastique',
  '23.0': 'Récolte prodts forestiers non ligneux',
  '23.1': "Fabric de verre et d'articles en verre",
  '23.2': 'Fabrication de produits réfractaires',
  '23.3': 'Fab. matériaux de constr. en terre cuite',
  '23.4': 'Fab. aut .prod. en céramiq. & porcelaine',
  '23.5': 'Fabrication de ciment, chaux et plâtre',
  '23.6': 'Fabric. ouvrage en béton, ciment, plâtre',
  '23.7': 'Taille, façonnage & finissage de pierres',
  '23.9': 'Fab. pdt abrasif & minér. non métal nca.',
  '24.0': "Services de soutien à l'expl. forestière",
  '24.1': 'Sidérurgie',
  '24.2': 'Fab. tube, profilé creux etc. en acier',
  '24.3': 'Fab. aut. prod. de 1ère transform. acier',
  '24.4': 'Prod. métaux précieux & aut. m. non fer.',
  '24.5': 'Fonderie',
  '25.1': 'Fab. élément en métal pour la construct.',
  '25.2': 'Fab. réservr, citerne & conteneur métal.',
  '25.3': 'Fab. générat. vapeur sf pr chauff. ctral',
  '25.4': "Fabrication d'armes et de munitions",
  '25.5': 'Forge, etc.; métallurgie des poudres',
  '25.6': 'Traitmnt & revêtmnt des métaux; usinage',
  '25.7': 'Fab. coutellerie, outillage & quincaill.',
  '25.9': "Fabrication d'autres ouvrages en métaux",
  '26.1': 'Fab. de composants & cartes électroniq.',
  '26.2': 'Fab. ordinateur & équipement périphériq.',
  '26.3': "Fabric. d'équipements de communication",
  '26.4': 'Fab. produit électronique grand public',
  '26.5': 'Fab. instr. mesure, navigat.; horlogerie',
  '26.6': 'Fab. éqpt irrad. médic. & électromedic.',
  '26.7': 'Fab. matériel optique et photographique',
  '26.8': 'Fab. de supports magnétiques et optiques',
  '27.1': 'Fab. moteur génér. transfo. & mat. élec.',
  '27.2': 'Fabric. pile & accumulateur électrique',
  '27.3': 'Fab. fil câble & mat. install. électriq.',
  '27.4': "Fabric. appareils d'éclairage électrique",
  '27.5': "Fabrication d'appareils ménagers",
  '27.9': "Fabric. d'autres matériels électriques",
  '28.1': "Fabrication de machines d'usage général",
  '28.2': "Fabric. autres machines d'usage général",
  '28.3': 'Fab. machines agricoles et forestières',
  '28.4': 'Fab. mach. formage métaux & mach.-outil',
  '28.9': "Fabric. autre machine d'usage spécifique",
  '29.1': 'Construction de véhicules automobiles',
  '29.2': 'Fabrication de carrosseries et remorques',
  '29.3': "Fabrication d'équipements automobiles",
  '30.1': 'Construction navale',
  '30.2': 'Const. loco. & autre mat. ferro. roulant',
  '30.3': 'Construction aéronautique et spatiale',
  '30.4': 'Constr. véhicules militaires de combat',
  '30.9': 'Fabric. de matériels de transport n.c.a.',
  '31.0': 'Fabrication de meubles',
  '31.1': 'Pêche en mer',
  '31.2': 'Pêche en eau douce',
  '32.1': 'Aquaculture en mer',
  '32.2': "Fabrication d'instruments de musique",
  '32.3': "Fabrication d'articles de sport",
  '32.4': 'Fabrication de jeux et jouets',
  '32.5': 'Fab. inst. & fournit. usage méd. & dent.',
  '32.9': 'Activités manufacturières n.c.a.',
  '33.1': 'Répar. ouvrage en métaux, mach. & équipt',
  '33.2': 'Install. de machines & équipt industriel',
  '35.1': 'Prod., transport & distrib. électricité',
  '35.2': 'Prod. & distrib. de combustibles gazeux',
  '35.3': 'Prod. & distrib. vapeur et air condit.',
  '36.0': "Captage, traitement & distribution d'eau",
  '37.0': 'Collecte et traitement des eaux usées',
  '38.1': 'Collecte des déchets',
  '38.2': 'Traitement et élimination des déchets',
  '38.3': 'Récupération',
  '39.0': 'Dépollution & autre sces gestion déchets',
  '41.1': 'Promotion immobilière',
  '41.2': 'Construc. bâtimnt résid. & non résident.',
  '42.1': 'Construction de route & de voies ferrées',
  '42.2': 'Construction de réseaux et de lignes',
  '42.9': 'Construc. autres ouvrages de génie civil',
  '43.1': 'Démolition et préparation des sites',
  '43.2': 'Travaux install. élect. plomberie & aut.',
  '43.3': 'Travaux de finition',
  '43.9': 'Autres travaux construction spécialisés',
  '45.1': 'Commerce de véhicules automobiles',
  '45.2': 'Entretien & répar. de véhicule auto.',
  '45.3': "Commerce d'équipements automobiles",
  '45.4': 'Commerce et réparation de motocycles',
  '46.1': 'Intermédiaires du commerce de gros',
  '46.2': 'Com. gros prod. agric. brut & anim. viv.',
  '46.3': 'Comm. gros prod. alim. boisson & tabac',
  '46.4': 'Commerce de gros de biens domestiques',
  '46.5': 'Comm. gros équipt. information & com.',
  '46.6': 'Commerce de gros autres équipts indust.',
  '46.7': 'Autres commerces de gros spécialisés',
  '46.9': 'Commerce de gros non spécialisé',
  '47.1': 'Comm. détail en magasin non spécialisé',
  '47.2': 'Com. dét. aliment. en magasin spécialisé',
  '47.3': 'Comm. détail carburant en mag. spéciali.',
  '47.4': 'Com. dét. équipt information & com. (ms)',
  '47.5': 'Com. dét. aut. éqpt du foyer (mag. spé.)',
  '47.6': 'Comm. dét. biens culturels & loisir (ms)',
  '47.7': 'Autre comm. détail en magasin spécialisé',
  '47.8': 'Commerce détail sur éventaires & marchés',
  '47.9': 'Com. dét. hors mag. éventair. ou marchés',
  '49.1': 'Transport ferrov. interurbain voyageur',
  '49.2': 'Transports ferroviaires de fret',
  '49.3': 'Autres transports terrestres de voyageur',
  '49.4': 'Transport routier de fret & sce déménagt',
  '49.5': 'Transports par conduites',
  '50.1': 'Transport maritime & côtier de passagers',
  '50.2': 'Transports maritimes et côtiers de fret',
  '50.3': 'Transports fluviaux de passagers',
  '50.4': 'Transports fluviaux de fret',
  '51.0': 'Extraction de houille',
  '51.1': 'Transports aériens de passagers',
  '51.2': 'Transp. aérien de fret & trans. spatiaux',
  '52.0': 'Extraction de lignite',
  '52.1': 'Entreposage et stockage',
  '52.2': 'Services auxiliaires des transports',
  '53.1': 'Activ. poste (obligation sce universel)',
  '53.2': 'Autres activités de poste et de courrier',
  '55.1': 'Hôtels et hébergement similaire',
  '55.2': 'Hébergt tourist. & aut. hbt courte durée',
  '55.3': 'Terrain camping & parc pr caravane etc.',
  '55.9': 'Autres hébergements',
  '56.1': 'Restaurant & serv. de restaurat. mobile',
  '56.2': 'Traiteur & autre service de restauration',
  '56.3': 'Débits de boissons',
  '58.1': 'Édition livre & périodiq. & aut. édition',
  '58.2': 'Édition de logiciels',
  '59.1': 'Activ. cinématogra., vidéo & télévision',
  '59.2': 'Enregistrement sonore & édition musicale',
  '60.1': 'Édition et diffusion de programmes radio',
  '60.2': 'Programmation de télévision & télédiff.',
  '61.0': 'Extraction de pétrole brut',
  '61.1': 'Télécommunications filaires',
  '61.2': 'Télécommunications sans fil',
  '61.3': 'Télécommunications par satellite',
  '61.9': 'Autres activités de télécommunication',
  '62.0': 'Extraction de gaz naturel',
  '63.1': 'Trt donnée, hébrgt etc.; portail Internt',
  '63.9': "Autres services d'information",
  '64.1': 'Intermédiation monétaire',
  '64.2': 'Activités des sociétés holding',
  '64.3': 'Fonds placement & entité financ. simil.',
  '64.9': 'Aut. act. finan. hs assur. & c. retrait.',
  '65.1': 'Assurance',
  '65.2': 'Réassurance',
  '65.3': 'Caisses de retraite',
  '66.1': 'Act. aux. sce financ. hs ass. & retraite',
  '66.2': 'Act. auxil. assurance & caisse retraite',
  '66.3': 'Gestion de fonds',
  '68.1': 'Activité marchands de biens immobiliers',
  '68.2': 'Loc. & exploi. bien immo. propre ou loué',
  '68.3': 'Activité immobilière pour cpte de tiers',
  '69.1': 'Activités juridiques',
  '69.2': 'Activités comptables',
  '70.1': 'Activités des sièges sociaux',
  '70.2': 'Conseil de gestion',
  '71.0': 'Extraction de minerais de fer',
  '71.1': "Activités d'architecture et d'ingénierie",
  '71.2': 'Activité de contrôle & analyse technique',
  '72.1': 'R&D en sciences physiques et naturelles',
  '72.2': 'R&D en sciences humaines et sociales',
  '72.9': 'Extr. aut. minerai de métaux non ferreux',
  '73.1': 'Publicité',
  '73.2': 'Études de marché et sondages',
  '74.1': 'Activités spécialisées de design',
  '74.2': 'Activités photographiques',
  '74.3': 'Traduction et interprétation',
  '74.9': 'Aut. act. spéc. scientif. & techn. nca.',
  '75.0': 'Activités vétérinaires',
  '77.1': 'Loc. & loc.-bail de véhicule automobile',
  '77.2': 'Loc. & loc.-bail bien perso. & domestiq.',
  '77.3': 'Loc. & loc.-bail aut. mach., éqpt & bien',
  '77.4': 'Loc-bail propr. intel., sf oeuvre avec ©',
  '78.1': "Activ. agence placement de main-d'oeuvre",
  '78.2': 'Activ. des agences de travail temporaire',
  '78.3': 'Aut. mise à dispo. de ressource humaine',
  '79.1': 'Activités agences de voyage & voyagistes',
  '79.9': 'Autre serv. réservation & activ. connexe',
  '80.1': 'Activités de sécurité privée',
  '80.2': 'Activités liées aux systèmes de sécurité',
  '80.3': "Activités d'enquête",
  '81.1': 'Act. combinée soutien lié aux bâtiments',
  '81.2': 'Exploit. gravière & sabl., extr. argile',
  '81.3': "Services d'aménagement paysager",
  '82.1': 'Activités administratives',
  '82.2': "Activités de centres d'appels",
  '82.3': 'Organisation salon profession. & congrès',
  '82.9': 'Activités soutien aux entreprises nca.',
  '84.1': 'Admin. générale, économique & sociale',
  '84.2': 'Services de prérogative publique',
  '84.3': 'Sécurité sociale obligatoire',
  '85.1': 'Enseignement pré-primaire',
  '85.2': 'Enseignement primaire',
  '85.3': 'Enseignement secondaire',
  '85.4': 'Enseigmnt sup. & post-second. non sup.',
  '85.5': "Autres activités d'enseignement",
  '85.6': "Activités de soutien à l'enseignement",
  '86.1': 'Activités hospitalières',
  '86.2': 'Activité des médecins et des dentistes',
  '86.9': 'Autres activités pour la santé humaine',
  '87.1': 'Hébergement médicalisé',
  '87.2': 'Hébrgt soc. hand., mal. mental & toxico.',
  '87.3': 'Hébgt soc. perso. âgées, hand. physiques',
  '87.9': 'Autres activités d’hébergement social',
  '88.1': 'Action soc. sans hbgt, per. âgée & hand.',
  '88.9': 'Autre action sociale sans hébergement',
  '89.1': 'Extr. minéraux chimiq. & engrais min.',
  '89.2': 'Extraction de tourbe',
  '89.3': 'Production de sel',
  '89.9': 'Autres activités extractives n.c.a.',
  '90.0': 'Act. créativ. artistiques & de spectacle',
  '91.0': 'Biblioth. archive musée & aut. act. cul.',
  '92.0': "Organisation jeux de hasard & d'argent",
  '93.1': 'Activités liées au sport',
  '93.2': 'Activités récréatives et de loisirs',
  '94.1': 'Act. organisations écon. patron. & prof.',
  '94.2': 'Activités des syndicats de salariés',
  '94.9': 'Act. autres organisations associatives',
  '95.1': 'Répar. ordinateur & équipt communication',
  '95.2': 'Réparation  biens personnel & domestique',
  '96.0': 'Autres services personnels',
  '97.0': 'Act. ménage: empl. de person. domestique',
  '98.1': 'Act. ménage : prod. biens (usage propre)',
  '98.2': 'Act. ménage : prod. serv. (usage propre)',
  '99.0': 'Act. organisations extraterritoriales',
  '10.11': 'Transf. & conserv.  viande de boucherie',
  '10.12': 'Transf. & conserv. de viande de volaille',
  '10.13': 'Préparation de produits à base de viande',
  '10.20': 'Transf. & conserv. poisson, crust., etc.',
  '10.31': 'Transf. et conserv. de pommes de terre',
  '10.32': 'Préparation de jus de fruits et légumes',
  '10.39': 'Aut. transf. & cons. de fruit et légume',
  '10.41': "Fabrication d'huiles et graisses",
  '10.42': 'Fab. de margarine & graisses similaires',
  '10.51': 'Expl. de laiteries et fabric. de fromage',
  '10.52': 'Fabrication de glaces et sorbets',
  '10.61': 'Travail des grains',
  '10.62': 'Fabrication de produits amylacés',
  '10.71': 'Fab. de pain et de pâtisserie fraîche',
  '10.72': 'Fab. pain, biscuit & pâtiss. de conserv.',
  '10.73': 'Fabrication de pâtes alimentaires',
  '10.81': 'Fabrication de sucre',
  '10.82': 'Fabric. de cacao, chocolat & confiseries',
  '10.83': 'Transformation du thé et du café',
  '10.84': 'Fabric. de condiments et assaisonnements',
  '10.85': 'Fabrication de plats préparés',
  '10.86': "Fab. d'aliment homogénéisé & diététique",
  '10.89': "Fab. d'autres prod. alimentaires n.c.a.",
  '10.91': "Fabric. d'aliments pour animaux de ferme",
  '10.92': 'Fab. aliments pour animaux de compagnie',
  '11.01': 'Prod. de boissons alcooliques distillées',
  '11.02': 'Production de vin (de raisin)',
  '11.03': 'Fabrication de cidre & de vins de fruits',
  '11.04': 'Prod. aut. boisson fermentée non distil.',
  '11.05': 'Fabrication de bière',
  '11.06': 'Fabrication de malt',
  '11.07': 'Ind. eaux & boissons rafraîchissantes',
  '12.00': 'Fabrication de produits à base de tabac',
  '13.10': 'Prépa. de fibres textiles et filature',
  '13.20': 'Tissage',
  '13.30': 'Ennoblissement textile',
  '13.91': "Fabrication d'étoffes à mailles",
  '13.92': "Fab. d'article textile, sauf habillement",
  '13.93': 'Fabrication de tapis et moquettes',
  '13.94': 'Fabric. de ficelles, cordes et filets',
  '13.95': 'Fabric. de non-tissés, sauf habillement',
  '13.96': 'Fab. autre textile techniq. & industriel',
  '13.99': "Fabrication d'autres textiles n.c.a.",
  '14.11': 'Fabrication de vêtements en cuir',
  '14.12': 'Fabrication de vêtements de travail',
  '14.13': 'Fabrication de vêtements de dessus',
  '14.14': 'Fabrication de vêtements de dessous',
  '14.19': 'Fabric. autres vêtements et accessoires',
  '14.20': "Fabrication d'articles en fourrure",
  '14.31': "Fabric. d'articles chaussants à mailles",
  '14.39': "Fabrication d'autres articles à mailles",
  '15.11': 'Prépa. cuirs; prép. & teinture fourrures',
  '15.12': 'Fab. art. voyage, maroquin., & sellerie',
  '15.20': 'Fabrication de chaussures',
  '16.10': 'Sciage et rabotage du bois',
  '16.21': 'Fabric.  placage et panneaux de bois',
  '16.22': 'Fabrication de parquets assemblés',
  '16.23': 'Fab. charpentes et autres menuiseries',
  '16.24': "Fabrication d'emballages en bois",
  '16.29': 'Fab. objet div. bois, liège, vann., etc.',
  '17.11': 'Fabrication de pâte à papier',
  '17.12': 'Fabrication de papier et de carton',
  '17.21': 'Fab. papier & carton & emball. pap.-car.',
  '17.22': 'Fab. article papier sanit. ou domestique',
  '17.23': "Fabrication d'articles de papeterie",
  '17.24': 'Fabrication de papiers peints',
  '17.29': 'Fab. aut. article en papier ou en carton',
  '18.11': 'Imprimerie de journaux',
  '18.12': 'Autre imprimerie (labeur)',
  '18.13': 'Activités de pré-presse',
  '18.14': 'Reliure et activités connexes',
  '18.20': "Reproduction d'enregistrements",
  '19.10': 'Cokéfaction',
  '19.20': 'Raffinage du pétrole',
  '20.11': 'Fabrication de gaz industriels',
  '20.12': 'Fabrication de colorants et de pigments',
  '20.13': 'Fab. aut. prod. chimique inorg. de base',
  '20.14': 'Fab. aut. prod. chimique org. de base',
  '20.15': "Fabric. de produits azotés et d'engrais",
  '20.16': 'Fabric. de matières plastiques de base',
  '20.17': 'Fabrication de caoutchouc synthétique',
  '20.20': 'Fab. pesticide & aut. prod. agrochimique',
  '20.30': 'Fab. de peinture, vernis, encre & mastic',
  '20.41': 'Fab. savon, détergent & prod. entretien',
  '20.42': 'Fab. parfum & produit pour la toilette',
  '20.51': 'Fabrication de produits explosifs',
  '20.52': 'Fabrication de colles',
  '20.53': "Fabrication d'huiles essentielles",
  '20.59': 'Fabric. autres produits chimiques n.c.a.',
  '20.60': 'Fab.  fibre artificielle ou synthétique',
  '21.10': 'Fab. de produits pharmaceutiques de base',
  '21.20': 'Fabric. de préparations pharmaceutiques',
  '22.11': 'Fabrication et rechapage de pneumatiques',
  '22.19': "Fabric. d'autres articles en caoutchouc",
  '22.21': 'Fab. plaque, feuille, tube,  etc. plast.',
  '22.22': "Fab. d'emballage en matière plastique",
  '22.23': 'Fab. élément mat. plastiq. pr construct.',
  '22.29': 'Fab. autre article en matière plastique',
  '23.11': 'Fabrication de verre plat',
  '23.12': 'Façonnage & transformation du verre plat',
  '23.13': 'Fabrication de verre creux',
  '23.14': 'Fabrication de fibres de verre',
  '23.19': 'Fab. & façonnage aut. article en verre',
  '23.20': 'Fabrication de produits réfractaires',
  '23.31': 'Fabrication de carreaux en céramique',
  '23.32': 'Fab. produit  construct. en terre cuite',
  '23.41': 'Fab. art. céramiq. usage domest. & déco.',
  '23.42': 'Fab. appareil sanitaire en céramique',
  '23.43': 'Fab. isolateur & pièce isolante céramiq.',
  '23.44': 'Fab. aut. prod. céram. à usage technique',
  '23.49': "Fabrication d'autres produits céramiques",
  '23.51': 'Fabrication de ciment',
  '23.52': 'Fabrication de chaux et plâtre',
  '23.61': 'Fab. élément en béton pour la construct.',
  '23.62': 'Fab. élément en plâtre pour la construc.',
  '23.63': "Fabrication de béton prêt à l'emploi",
  '23.64': 'Fabrication de mortiers et bétons secs',
  '23.65': "Fabrication d'ouvrages en fibre-ciment",
  '23.69': 'Fab. aut. ouvrage béton, ciment, plâtre',
  '23.70': 'Taille, façonnage & finissage de pierres',
  '23.91': 'Fabrication de produits abrasifs',
  '23.99': 'Fab. aut. prod. minéraux non métal. nca.',
  '24.10': 'Sidérurgie',
  '24.20': 'Fab. tube, profilé creux etc. en acier',
  '24.31': 'Étirage à froid de barres',
  '24.32': 'Laminage à froid de feuillards',
  '24.33': 'Profilage à froid par formage ou pliage',
  '24.34': 'Tréfilage à froid',
  '24.41': 'Production de métaux précieux',
  '24.42': "Métallurgie de l'aluminium",
  '24.43': 'Métallurgie du Pb, du Zn ou du Sn',
  '24.44': 'Métallurgie du cuivre',
  '24.45': 'Métallurgie autres métaux non ferreux',
  '24.46': 'Élaboration et transform. mat. nucléaire',
  '24.51': 'Fonderie de fonte',
  '24.52': "Fonderie d'acier",
  '24.53': 'Fonderie de métaux légers',
  '24.54': "Fonderie d'autres métaux non ferreux",
  '25.11': 'Fab. structure métal. & partie structure',
  '25.12': 'Fabric. de portes et fenêtres en métal',
  '25.21': 'Fab. radiat. & chaudière pr chauf. ctral',
  '25.29': 'Fab. aut. réservr, citerne, etc. métal.',
  '25.30': 'Fab. générat. vapeur sf pr chauff. ctral',
  '25.40': "Fabrication d'armes et de munitions",
  '25.50': 'Forge, etc.; métallurgie des poudres',
  '25.61': 'Traitement et revêtement des métaux',
  '25.62': 'Usinage',
  '25.71': 'Fabrication de coutellerie',
  '25.72': 'Fabrication de serrures et de ferrures',
  '25.73': "Fabrication d'outillage",
  '25.91': 'Fab. fût & emballage métalliq. similaire',
  '25.92': "Fabric. d'emballages métalliques légers",
  '25.93': 'Fab. art.  fil métal., chaîne & ressort',
  '25.94': 'Fabrication de vis et de boulons',
  '25.99': 'Fabric. autres prod. métalliques n.c.a.',
  '26.11': 'Fabrication de composants électroniques',
  '26.12': 'Fab de cartes électroniques assemblées',
  '26.20': 'Fab. ordinateur & équipement périphériq.',
  '26.30': "Fabric. d'équipements de communication",
  '26.40': 'Fab. produit électronique grand public',
  '26.51': 'Fab. instrum. de mesure & de navigation',
  '26.52': 'Horlogerie',
  '26.60': 'Fab. éqpt irrad. médic. & électromedic.',
  '26.70': 'Fab. matériel optique et photographique',
  '26.80': 'Fab. de supports magnétiques et optiques',
  '27.11': 'Fab. moteur génér. transfo. & mat. élec.',
  '27.12': 'Fab. mat. de distrib. & de cde électri.',
  '27.20': 'Fabric. pile & accumulateur électrique',
  '27.31': 'Fabrication de câbles de fibres optiques',
  '27.32': 'Fab. aut. fil & câble éltron. ou éltriq.',
  '27.33': 'Fabric. matériel installation électrique',
  '27.40': "Fabric. appareils d'éclairage électrique",
  '27.51': "Fabrication d'appareils électroménagers",
  '27.52': 'Fab. appareils ménagers non électriques',
  '27.90': "Fabric. d'autres matériels électriques",
  '28.11': 'Fab. moteur & turb. sf pr avion & véhic.',
  '28.12': 'Fab. équipement hydraulique & pneumatiq.',
  '28.13': "Fabric. d'autres pompes et compresseurs",
  '28.14': 'Fabric. autres articles de robinetterie',
  '28.15': 'Fab. engrenage & organe méca. transmis.',
  '28.21': 'Fabrication de fours et brûleurs',
  '28.22': 'Fab. matériel de levage & de manutention',
  '28.23': 'Fab. machine équipt bureau (sf ordinat.)',
  '28.24': 'Fab. outillage portatif à moteur incorp.',
  '28.25': 'Fab. équipt aérauliq. & frigorifiq. ind.',
  '28.29': "Fab. machines diverses d'usage général",
  '28.30': 'Fab. machines agricoles et forestières',
  '28.41': 'Fab. de machines de formage des métaux',
  '28.49': "Fabrication d'autres machines-outils",
  '28.91': 'Fabric. de machines pour la métallurgie',
  '28.92': 'Fab. machine pour extraction ou constr.',
  '28.93': "Fab. machine pour l'indus. agro-aliment.",
  '28.94': 'Fab. machine pour industries textiles',
  '28.95': 'Fab. machine pr indus. papier & carton',
  '28.96': 'Fab. machine pr trav. du caoutch, plast.',
  '28.99': 'Fab. autre machine usage spécifi. n.c.a.',
  '29.10': 'Construction de véhicules automobiles',
  '29.20': 'Fabrication de carrosseries et remorques',
  '29.31': 'Fab. équipt électriq. & électron. auto.',
  '29.32': "Fabric. d'autres équipements automobiles",
  '30.11': 'Construct. navires & structure flottante',
  '30.12': 'Construction de bateaux de plaisance',
  '30.20': 'Const. loco. & autre mat. ferro. roulant',
  '30.30': 'Construction aéronautique et spatiale',
  '30.40': 'Constr. véhicules militaires de combat',
  '30.91': 'Fabrication de motocycles',
  '30.92': 'Fab. bicyclette & véhic. pour invalides',
  '30.99': 'Fab. aut. équipement de transport n.c.a.',
  '31.01': 'Fab. de meubles de bureau et de magasin',
  '31.02': 'Fabrication de meubles de cuisine',
  '31.03': 'Fabrication de matelas',
  '31.09': "Fabrication d'autres meubles",
  '32.11': 'Frappe de monnaie',
  '32.12': 'Fab. article de joaillerie et bijouterie',
  '32.13': 'Fab. art. bijout. fantaisie & similaire',
  '32.20': "Fabrication d'instruments de musique",
  '32.30': "Fabrication d'articles de sport",
  '32.40': 'Fabrication de jeux et jouets',
  '32.50': 'Fab. inst. & fournit. usage méd. & dent.',
  '32.91': 'Fabrication d’articles de brosserie',
  '32.99': 'Autres activités manufacturières n.c.a.',
  '33.11': "Réparation d'ouvrages en métaux",
  '33.12': 'Répar. machine & équipement mécaniques',
  '33.13': 'Répar. matériel électronique & optique',
  '33.14': "Réparation d'équipements électriques",
  '33.15': 'Réparation et maintenance navale',
  '33.16': 'Répar. & maint. aéronef & eng. spatiaux',
  '33.17': "Répar. & maint. d'aut. équipt transport",
  '33.19': "Réparation d'autres équipements",
  '33.20': 'Install. de machines & équipt industriel',
  '35.11': "Production d'électricité",
  '35.12': "Transport d'électricité",
  '35.13': "Distribution d'électricité",
  '35.14': "Commerce d'électricité",
  '35.21': 'Production de combustibles gazeux',
  '35.22': 'Distrib. combustible gazeux pr conduites',
  '35.23': 'Commerce combustible gazeux par conduite',
  '35.30': 'Prod. & distrib. vapeur et air condit.',
  '36.00': "Captage, traitement & distribution d'eau",
  '37.00': 'Collecte et traitement des eaux usées',
  '38.11': 'Collecte des déchets non dangereux',
  '38.12': 'Collecte des déchets dangereux',
  '38.21': 'Traitmnt & élimin. déchets non dangereux',
  '38.22': 'Traitmnt & élimination déchets dangereux',
  '38.31': "Démantèlement d'épaves",
  '38.32': 'Récupération de déchets triés',
  '39.00': 'Dépollution & autre sces gestion déchets',
  '41.10': 'Promotion immobilière',
  '41.20': 'Construc. bâtimnt résid. & non résident.',
  '42.11': 'Construction de routes et autoroutes',
  '42.12': 'Const. voie ferrée surface & souterraine',
  '42.13': 'Construction de ponts et tunnels',
  '42.21': 'Construction de réseaux pour fluides',
  '42.22': 'Const. réseaux électriq. & de télécom.',
  '42.91': 'Construc. ouvrages maritimes et fluviaux',
  '42.99': 'Constr. aut. ouvrage de génie civil nca.',
  '43.11': 'Travaux de démolition',
  '43.12': 'Travaux de préparation des sites',
  '43.13': 'Forages et sondages',
  '43.21': 'Installation électrique',
  '43.22': 'Trav. plomberie chauffage & condit. air',
  '43.29': "Autres travaux d'installation",
  '43.31': 'Travaux de plâtrerie',
  '43.32': 'Travaux de menuiserie',
  '43.33': 'Travaux revêtement des sols et des murs',
  '43.34': 'Travaux de peinture et vitrerie',
  '43.39': 'Autres travaux de finition',
  '43.91': 'Travaux de couverture',
  '43.99': 'Aut. travaux construc. spécialisés nca.',
  '45.11': 'Comm. de voiture & véhicule auto. léger',
  '45.19': "Commerce d'autres véhicules automobiles",
  '45.20': 'Entretien & répar. de véhicule auto.',
  '45.31': "Commerce de gros d'équipement automobile",
  '45.32': 'Commerce de détail équipement automobile',
  '45.40': 'Commerce et réparation de motocycles',
  '46.11': 'Interm. du comm. en produits agricoles',
  '46.12': 'Int. comm. comb. mét. minér. & pd. chim.',
  '46.13': 'Interm. comm. bois & matériaux construc.',
  '46.14': 'Int. comm. équipt indus., navire & avion',
  '46.15': 'Int. comm. meuble, art. ménage & quinc.',
  '46.16': 'Int. comm. textile, habillt & assimil.',
  '46.17': 'Int. comm. en denrées, boissons & tabac',
  '46.18': 'Int. spécialis. comm. aut. prod. spécif.',
  '46.19': 'Interm. du commerce en produits divers',
  '46.21': 'Com gros céréal. tab. brt & alim. bétail',
  '46.22': 'Commerce de gros de fleurs et plantes',
  '46.23': "Commerce de gros d'animaux vivants",
  '46.24': 'Commerce de gros de cuirs et peaux',
  '46.31': 'Commerce de gros de fruits et légumes',
  '46.32': 'Comm. gros viande & prod. à base  viande',
  '46.33': 'Com. gros prod. laitier oeuf & mat. grse',
  '46.34': 'Commerce de gros de boissons',
  '46.35': 'Comm. gros de produits à base de tabac',
  '46.36': 'Com. gros de sucre chocolat & confiserie',
  '46.37': 'Comm. gros de café, thé, cacao et épices',
  '46.38': 'Com. gros aut. alim. yc poisson crustacé',
  '46.39': 'Com. gros non spéc. denrée boisson tabac',
  '46.41': 'Commerce de gros de textiles',
  '46.42': "Commerce gros d'habillement & chaussures",
  '46.43': 'Commerce de gros appareil électroménager',
  '46.44': 'Com. gros vaisselle verrerie prod. entr.',
  '46.45': 'Com. gros parfumerie & produit de beauté',
  '46.46': 'Comm. gros de produits pharmaceutiques',
  '46.47': 'Com. gros meuble tapis appareil éclaira.',
  '46.48': 'Com. gros artic. horlogerie & bijouterie',
  '46.49': "Commerce gros d'autres biens domestiques",
  '46.51': 'Comm. gros ordi. éqpt périph. & logiciel',
  '46.52': 'Cg éqpt & composant électron. & télécom.',
  '46.61': 'Commerce de gros de matériel agricole',
  '46.62': 'Commerce de gros de machines-outils',
  '46.63': 'Com. gros machine pr extrac., constr. GC',
  '46.64': 'Com. gros machine pr ind. text. & habil.',
  '46.65': 'Commerce de gros de mobilier de bureau',
  '46.66': 'Com. gros autre machine & équipt bureau',
  '46.69': 'Commerce de gros autre machine & équipt',
  '46.71': 'Com. gros combustible & produits annexes',
  '46.72': 'Commerce de gros de minerais et métaux',
  '46.73': 'Cg bois, mat. construc. & app. sanitaire',
  '46.74': 'Cg quincail. & fournit. plombr. & chauf.',
  '46.75': 'Commerce de gros de produits chimiques',
  '46.76': "Commerce gros d'aut. prod. intermédiaire",
  '46.77': 'Commerce de gros de déchets et débris',
  '46.90': 'Commerce de gros non spécialisé',
  '47.11': 'Comm. dét. mag. non spéc. à prédo. alim.',
  '47.19': 'Autre comm. détail en magasin non spéc.',
  '47.21': 'Com. détail fruit & légume en mag. spéc.',
  '47.22': 'Com. dét. viande & prdt avec viande (ms)',
  '47.23': 'Comm. détail poisson crustacé etc. (ms)',
  '47.24': 'Comm. dét. pain pâtiss. & confiser. (ms)',
  '47.25': 'Com. détail boisson en magasin spéciali.',
  '47.26': 'Comm. dét. produit à base de tabac (ms)',
  '47.29': 'Aut. com. détail alim. en mag. spéciali.',
  '47.30': 'Comm. détail carburant en mag. spéciali.',
  '47.41': 'Com. dét ordi. un. périph. & logicl (ms)',
  '47.42': 'Comm. dét. matériel télécom. (ms)',
  '47.43': 'Comm. dét. matériels audio/vidéo (ms)',
  '47.51': 'Com. dét. textiles en magasin spécialisé',
  '47.52': 'Comm. dét. quinca. peinture & verre (ms)',
  '47.53': 'Cd tapis moquette & revêt. mur sol (ms)',
  '47.54': 'Comm. dét.  appareil électroménager (ms)',
  '47.59': 'Com. dét. meub. éclair. & aut. art. mén.',
  '47.61': 'Comm. dét. livres en magasin spécialisé',
  '47.62': 'Comm. détail journaux & papeterie (ms)',
  '47.63': 'Comm. dét. enreg. musicaux & vidéo (ms)',
  '47.64': 'Com. dét. articles de sport en mag. spé.',
  '47.65': 'Com. dét. jeux & jouets en mag. spécial.',
  '47.71': 'Com. dét. habillement en mag. spécialisé',
  '47.72': 'Comm. dét. chaussure & article cuir (ms)',
  '47.73': 'Comm. dét. produits pharmaceutiques (ms)',
  '47.74': 'Com. dét. art. médicaux & orthopéd. (ms)',
  '47.75': 'Com. dét. parfumerie & prodt beauté (ms)',
  '47.76': 'Com. dét. fleur plante anim. cie + alim.',
  '47.77': 'Com. dét. art. horlogerie & bijout. (ms)',
  '47.78': 'Aut. comm. dét. biens neufs en mag. spé.',
  '47.79': "Comm. détail biens d'occasion en magasin",
  '47.81': 'Cd alimentaire sur éventaire & marché',
  '47.82': 'Cd textiles habillt & chauss. s/marchés',
  '47.89': 'Aut. com. dét. sur éventaires & marchés',
  '47.91': 'Vente à distance',
  '47.99': 'Aut. comm. dét. hors mag. évent., marché',
  '49.10': 'Transport ferrov. interurbain voyageur',
  '49.20': 'Transports ferroviaires de fret',
  '49.31': 'Transport urbain & suburbain de voyageur',
  '49.32': 'Transports de voyageurs par taxis',
  '49.39': 'Aut. transport terrestre voyageurs nca.',
  '49.41': 'Transports routiers de fret',
  '49.42': 'Services de déménagement',
  '49.50': 'Transports par conduites',
  '50.10': 'Transport maritime & côtier de passagers',
  '50.20': 'Transports maritimes et côtiers de fret',
  '50.30': 'Transports fluviaux de passagers',
  '50.40': 'Transports fluviaux de fret',
  '51.10': 'Transports aériens de passagers',
  '51.21': 'Transports aériens de fret',
  '51.22': 'Transports spatiaux',
  '52.10': 'Entreposage et stockage',
  '52.21': 'Sces auxiliaires de transport terrestre',
  '52.22': 'Sces auxiliaires des transports par eau',
  '52.23': 'Sces auxiliaires des transports aériens',
  '52.24': 'Manutention',
  '52.29': 'Autre service auxiliaires des transports',
  '53.10': 'Activ. poste (obligation sce universel)',
  '53.20': 'Autres activités de poste et de courrier',
  '55.10': 'Hôtels et hébergement similaire',
  '55.20': 'Hébergt tourist. & aut. hbt courte durée',
  '55.30': 'Terrain camping & parc pr caravane etc.',
  '55.90': 'Autres hébergements',
  '56.10': 'Restaurant & serv. de restaurat. mobile',
  '56.21': 'Services des traiteurs',
  '56.29': 'Autres services de restauration',
  '56.30': 'Débits de boissons',
  '58.11': 'Édition de livres',
  '58.12': "Édition répertoires & fichiers d'adresse",
  '58.13': 'Édition de journaux',
  '58.14': 'Édition de revues et périodiques',
  '58.19': "Autres activités d'édition",
  '58.21': 'Édition de jeux électroniques',
  '58.29': "Édition d'autres logiciels",
  '59.11': 'Prod. film cinémato. vidéo & pgm. télé.',
  '59.12': 'Post-production film & prog. télévision',
  '59.13': 'Distribution film vidéo & pgm. télé.',
  '59.14': 'Projection de films cinématographiques',
  '59.20': 'Enregistrement sonore & édition musicale',
  '60.10': 'Édition et diffusion de programmes radio',
  '60.20': 'Programmation de télévision & télédiff.',
  '61.10': 'Télécommunications filaires',
  '61.20': 'Télécommunications sans fil',
  '61.30': 'Télécommunications par satellite',
  '61.90': 'Autres activités de télécommunication',
  '62.01': 'Programmation informatique',
  '62.02': 'Conseil informatique',
  '62.03': "Gestion d'installations informatiques",
  '62.09': 'Autres activités informatiques',
  '63.11': 'Traitt donnée, hébergt & activ. connexe',
  '63.12': 'Portails Internet',
  '63.91': 'Activités des agences de presse',
  '63.99': "Autres services d'information n.c.a.",
  '64.11': 'Activités de banque centrale',
  '64.19': 'Autres intermédiations monétaires',
  '64.20': 'Activités des sociétés holding',
  '64.30': 'Fonds placement & entité financ. simil.',
  '64.91': 'Crédit-bail',
  '64.92': 'Autre distribution de crédit',
  '64.99': 'Aut. act. finan. hs as. & c. retra. nca.',
  '65.11': 'Assurance vie',
  '65.12': 'Autres assurances',
  '65.20': 'Réassurance',
  '65.30': 'Caisses de retraite',
  '66.11': 'Administration de marchés financiers',
  '66.12': 'Courtage valeur mobilière & marchandise',
  '66.19': 'Aut. act. aux. sce fin., hs ass. & retr.',
  '66.21': 'Évaluation des risques et dommages',
  '66.22': "Act. des agents & courtiers d'assurances",
  '66.29': 'Aut. act. aux. assur. & caisse retraite',
  '66.30': 'Gestion de fonds',
  '68.10': 'Activité marchands de biens immobiliers',
  '68.20': 'Loc. & exploi. bien immo. propre ou loué',
  '68.31': 'Agences immobilières',
  '68.32': 'Administration de biens immobiliers',
  '69.10': 'Activités juridiques',
  '69.20': 'Activités comptables',
  '70.10': 'Activités des sièges sociaux',
  '70.21': 'Conseil en relation publique & communic.',
  '70.22': 'Conseil pr affaire & aut. cons. gestion',
  '71.11': "Activités d'architecture",
  '71.12': "Activités d'ingénierie",
  '71.20': 'Activité de contrôle & analyse technique',
  '72.11': 'Recherche-développemnt en biotechnologie',
  '72.19': 'R&D : aut. sciences physique & naturelle',
  '72.20': 'R&D en sciences humaines et sociales',
  '73.11': 'Activités des agences de publicité',
  '73.12': 'Régie publicitaire de médias',
  '73.20': 'Études de marché et sondages',
  '74.10': 'Activités spécialisées de design',
  '74.20': 'Activités photographiques',
  '74.30': 'Traduction et interprétation',
  '74.90': 'Aut. act. spéc. scientif. & techn. nca.',
  '75.00': 'Activités vétérinaires',
  '77.11': 'Loc. & loc.-bail voit. & v. auto. léger',
  '77.12': 'Location et location-bail de camions',
  '77.21': 'Loc. & loc.-bail article loisir & sport',
  '77.22': 'Location de vidéocassette & disque vidéo',
  '77.29': 'Loc. & loc.-bail aut. bien perso. & dom.',
  '77.31': 'Loc. & loc.-bail machine & éqpt agricole',
  '77.32': 'Loc. & loc.-bail mach. & éqpt pr constr.',
  '77.33': 'Loc. & loc.-bail mach. bur. & mat. info.',
  '77.34': 'Loc. & loc.-bail mat. transport par eau',
  '77.35': 'Loc. & loc.-bail mat. transport aérien',
  '77.39': 'Loc. & loc.-bail machi. éqpt & bien div.',
  '77.40': 'Loc-bail propr. intel., sf oeuvre avec ©',
  '78.10': "Activ. agence placement de main-d'oeuvre",
  '78.20': 'Activ. des agences de travail temporaire',
  '78.30': 'Aut. mise à dispo. de ressource humaine',
  '79.11': 'Activités des agences de voyage',
  '79.12': 'Activités des voyagistes',
  '79.90': 'Autre serv. réservation & activ. connexe',
  '80.10': 'Activités de sécurité privée',
  '80.20': 'Activités liées aux systèmes de sécurité',
  '80.30': "Activités d'enquête",
  '81.10': 'Act. combinée soutien lié aux bâtiments',
  '81.21': 'Nettoyage courant des bâtiments',
  '81.22': 'Aut. act. nettoyage bâtim. & nett. ind.',
  '81.29': 'Autres activités de nettoyage',
  '81.30': "Services d'aménagement paysager",
  '82.11': 'Services admin. combinés de bureau',
  '82.19': 'Photocopie & aut. act. spé. sout. bureau',
  '82.20': "Activités de centres d'appels",
  '82.30': 'Organisation salon profession. & congrès',
  '82.91': 'Act. recouv. fac. & info. fin. s/client.',
  '82.92': 'Activités de conditionnement',
  '82.99': 'Autre activité de soutien aux entr. nca.',
  '84.11': 'Administration publique générale',
  '84.12': 'A. p. santé form. cult. & soc. (sf sécu)',
  '84.13': 'Adm. publique des activités économiques',
  '84.21': 'Affaires étrangères',
  '84.22': 'Défense',
  '84.23': 'Justice',
  '84.24': 'Activités d’ordre public et de sécurité',
  '84.25': 'Services du feu et de secours',
  '84.30': 'Sécurité sociale obligatoire',
  '85.10': 'Enseignement pré-primaire',
  '85.20': 'Enseignement primaire',
  '85.31': 'Enseignement secondaire général',
  '85.32': 'Enseignemt secondaire techn. ou profess.',
  '85.41': 'Enseignement post-secondaire non sup.',
  '85.42': 'Enseignement supérieur',
  '85.51': 'Enseigmnt discipl. sport. & act. loisir.',
  '85.52': 'Enseignement culturel',
  '85.53': 'Enseignement de la conduite',
  '85.59': 'Enseignements divers',
  '85.60': "Activités de soutien à l'enseignement",
  '86.10': 'Activités hospitalières',
  '86.21': 'Activité des médecins généralistes',
  '86.22': 'Activité des médecins spécialistes',
  '86.23': 'Pratique dentaire',
  '86.90': 'Autres activités pour la santé humaine',
  '87.10': 'Hébergement médicalisé',
  '87.20': 'Hébrgt soc. hand., mal. mental & toxico.',
  '87.30': 'Hébgt soc. perso. âgées, hand. physiques',
  '87.90': 'Autres activités d’hébergement social',
  '88.10': 'Action soc. sans hbgt, per. âgée & hand.',
  '88.91': 'Action soc. sans hbrgt pr jeunes enfants',
  '88.99': 'Autre action sociale sans hébrgemnt nca.',
  '90.01': 'Arts du spectacle vivant',
  '90.02': 'Activités de soutien au spectacle vivant',
  '90.03': 'Création artistique',
  '90.04': 'Gestion de salles de spectacles',
  '91.01': 'Gestion des bibliothèques & des archives',
  '91.02': 'Gestion des musées',
  '91.03': 'Gestion site histor. & attraction simil.',
  '91.04': 'Gest. jardin bota. & zoo. & réserv. nat.',
  '92.00': "Organisation jeux de hasard & d'argent",
  '93.11': "Gestion d'installations sportives",
  '93.12': 'Activités de clubs de sports',
  '93.13': 'Activité des centres de culture physique',
  '93.19': 'Autres activités liées au sport',
  '93.21': 'Act. parcs attractions & parcs à thèmes',
  '93.29': 'Autres activités récréative & de loisirs',
  '94.11': 'Act. organisations patronale & consul.',
  '94.12': 'Act. des organisations professionnelles',
  '94.20': 'Activités des syndicats de salariés',
  '94.91': 'Activités des organisations religieuses',
  '94.92': 'Activités des organisations politiques',
  '94.99': 'Act. organisations associatives nca.',
  '95.11': 'Répar. ordinateur & équipt périphérique',
  '95.12': 'Réparation équipements de communication',
  '95.21': 'Réparation prdts électroniq. grd public',
  '95.22': 'Répar. électromén. & éqpt maison & jard.',
  '95.23': 'Réparation chaussures & articles en cuir',
  '95.24': "Réparation meubles & d'équipt du foyer",
  '95.25': 'Répar.articles horlogerie & bijouterie',
  '95.29': 'Répar. aut. biens personnel & domestique',
  '96.01': 'Blanchisserie-teinturerie',
  '96.02': 'Coiffure et soins de beauté',
  '96.03': 'Services funéraires',
  '96.04': 'Entretien corporel',
  '96.09': 'Autres services personnels n.c.a.',
  '97.00': 'Act. ménage: empl. de person. domestique',
  '98.10': 'Act. ménage : prod. biens (usage propre)',
  '98.20': 'Act. ménage : prod. serv. (usage propre)',
  '99.00': 'Act. organisations extraterritoriales',
  '01': 'Cult. & prod. animale, chasse & sce ann.',
  '01.11Z': 'Cult céréale, légumineuse, graine oléag.',
  '01.12Z': 'Culture du riz',
  '01.13Z': 'Cult. légume, melon, racine & tubercule',
  '01.14Z': 'Culture de la canne à sucre',
  '01.15Z': 'Culture du tabac',
  '01.16Z': 'Culture de plantes à fibres',
  '01.19Z': 'Autres cultures non permanentes',
  '01.21Z': 'Culture de la vigne',
  '01.22Z': 'Culture fruits tropicaux et subtropicaux',
  '01.23Z': "Culture d'agrumes",
  '01.24Z': 'Culture de fruits à pépins et à noyau',
  '01.25Z': "Cult. d'aut. fruits & de fruits à coque",
  '01.26Z': 'Culture de fruits oléagineux',
  '01.27Z': 'Culture de plantes à boissons',
  '01.28Z': 'Cult. plante aromatiq. médicin. pharma.',
  '01.29Z': 'Autres cultures permanentes',
  '01.30Z': 'Reproduction de plantes',
  '01.41Z': 'Élevage de vaches laitières',
  '01.42Z': "Élevage d'autres bovins et de buffles",
  '01.43Z': "Élevage de chevaux et d'autres équidés",
  '01.44Z': "Élevage de chameaux & d'autres camélidés",
  '01.45Z': "Élevage d'ovins et de caprins",
  '01.46Z': 'Élevage de porcins',
  '01.47Z': 'Élevage de volailles',
  '01.49Z': "Élevage d'autres animaux",
  '01.50Z': 'Culture et élevage associés',
  '01.61Z': 'Activités de soutien aux cultures',
  '01.62Z': 'Activités de soutien à la prod. animale',
  '01.63Z': 'Traitement primaire des récoltes',
  '01.64Z': 'Traitement des semences',
  '01.70Z': 'Chasse, piégeage et services annexes',
  '02': 'Sylviculture et exploitation forestière',
  '02.10Z': 'Sylviculture & autres act. forestières',
  '02.20Z': 'Exploitation forestière',
  '02.30Z': 'Récolte prodts forestiers non ligneux',
  '02.40Z': "Services de soutien à l'expl. forestière",
  '03': 'Pêche et aquaculture',
  '03.11Z': 'Pêche en mer',
  '03.12Z': 'Pêche en eau douce',
  '03.21Z': 'Aquaculture en mer',
  '03.22Z': 'Aquaculture en eau douce',
  '05': 'Extraction de houille et de lignite',
  '05.10Z': 'Extraction de houille',
  '05.20Z': 'Extraction de lignite',
  '06': "Extraction d'hydrocarbures",
  '06.10Z': 'Extraction de pétrole brut',
  '06.20Z': 'Extraction de gaz naturel',
  '07': 'Extraction de minerais métalliques',
  '07.10Z': 'Extraction de minerais de fer',
  '07.21Z': "Extr. de minerais d'uranium & de thorium",
  '07.29Z': 'Extr. aut. minerai de métaux non ferreux',
  '08': 'Autres industries extractives',
  '08.11Z': 'Extr. pierre ornement. & construct. etc.',
  '08.12Z': 'Exploit. gravière & sabl., extr. argile',
  '08.91Z': 'Extr. minéraux chimiq. & engrais min.',
  '08.92Z': 'Extraction de tourbe',
  '08.93Z': 'Production de sel',
  '08.99Z': 'Autres activités extractives n.c.a.',
  '09': 'Sces de soutien aux indust. extractives',
  '09.10Z': "Act. de soutien à l'extr. hydrocarbures",
  '09.90Z': 'Act. de soutien aut. indus. extractives',
  '10.11Z': 'Transf. & conserv.  viande de boucherie',
  '10.12Z': 'Transf. & conserv. de viande de volaille',
  '10.13A': 'Prépa. indust. produits à base de viande',
  '10.13B': 'Charcuterie',
  '10.20Z': 'Transf. & conserv. poisson, crust., etc.',
  '10.31Z': 'Transf. et conserv. de pommes de terre',
  '10.32Z': 'Préparation de jus de fruits et légumes',
  '10.39A': 'Autre transf. et conserv. de légumes',
  '10.39B': 'Transformation et conservation de fruits',
  '10.41A': "Fabrication d'huiles et graisses brutes",
  '10.41B': "Fab. d'huiles et graisses raffinées",
  '10.42Z': 'Fab. de margarine & graisses similaires',
  '10.51A': 'Fab. de lait liquide & de produits frais',
  '10.51B': 'Fabrication de beurre',
  '10.51C': 'Fabrication de fromage',
  '10.51D': "Fabrication d'autres produits laitiers",
  '10.52Z': 'Fabrication de glaces et sorbets',
  '10.61A': 'Meunerie',
  '10.61B': 'Autres activités du travail des grains',
  '10.62Z': 'Fabrication de produits amylacés',
  '10.71A': 'Fab. indus. de pain & pâtisserie fraîche',
  '10.71B': 'Cuisson de produits de boulangerie',
  '10.71C': 'Boulangerie et boulangerie-pâtisserie',
  '10.71D': 'Pâtisserie',
  '10.72Z': 'Fab. pain, biscuit & pâtiss. de conserv.',
  '10.73Z': 'Fabrication de pâtes alimentaires',
  '10.81Z': 'Fabrication de sucre',
  '10.82Z': 'Fabric. de cacao, chocolat & confiseries',
  '10.83Z': 'Transformation du thé et du café',
  '10.84Z': 'Fabric. de condiments et assaisonnements',
  '10.85Z': 'Fabrication de plats préparés',
  '10.86Z': "Fab. d'aliment homogénéisé & diététique",
  '10.89Z': "Fab. d'autres prod. alimentaires n.c.a.",
  '10.91Z': "Fabric. d'aliments pour animaux de ferme",
  '10.92Z': 'Fab. aliments pour animaux de compagnie',
  '11.01Z': 'Prod. de boissons alcooliques distillées',
  '11.02A': 'Fabrication de vins effervescents',
  '11.02B': 'Vinification',
  '11.03Z': 'Fabrication de cidre & de vins de fruits',
  '11.04Z': 'Prod. aut. boisson fermentée non distil.',
  '11.05Z': 'Fabrication de bière',
  '11.06Z': 'Fabrication de malt',
  '11.07A': 'Industrie des eaux de table',
  '11.07B': 'Production de boissons rafraîchissantes',
  '12.00Z': 'Fabrication de produits à base de tabac',
  '13.10Z': 'Prépa. de fibres textiles et filature',
  '13.20Z': 'Tissage',
  '13.30Z': 'Ennoblissement textile',
  '13.91Z': "Fabrication d'étoffes à mailles",
  '13.92Z': "Fab. d'article textile, sauf habillement",
  '13.93Z': 'Fabrication de tapis et moquettes',
  '13.94Z': 'Fabric. de ficelles, cordes et filets',
  '13.95Z': 'Fabric. de non-tissés, sauf habillement',
  '13.96Z': 'Fab. autre textile techniq. & industriel',
  '13.99Z': "Fabrication d'autres textiles n.c.a.",
  '14.11Z': 'Fabrication de vêtements en cuir',
  '14.12Z': 'Fabrication de vêtements de travail',
  '14.13Z': 'Fabrication de vêtements de dessus',
  '14.14Z': 'Fabrication de vêtements de dessous',
  '14.19Z': 'Fabric. autres vêtements et accessoires',
  '14.20Z': "Fabrication d'articles en fourrure",
  '14.31Z': "Fabric. d'articles chaussants à mailles",
  '14.39Z': "Fabrication d'autres articles à mailles",
  '15.11Z': 'Prépa. cuirs; prép. & teinture fourrures',
  '15.12Z': 'Fab. art. voyage, maroquin., & sellerie',
  '15.20Z': 'Fabrication de chaussures',
  '16.10A': 'Sciage & rabotage bois, sf imprégnation',
  '16.10B': 'Imprégnation du bois',
  '16.21Z': 'Fabric.  placage et panneaux de bois',
  '16.22Z': 'Fabrication de parquets assemblés',
  '16.23Z': 'Fab. charpentes et autres menuiseries',
  '16.24Z': "Fabrication d'emballages en bois",
  '16.29Z': 'Fab. objet div. bois, liège, vann., etc.',
  '17.11Z': 'Fabrication de pâte à papier',
  '17.12Z': 'Fabrication de papier et de carton',
  '17.21A': 'Fabrication de carton ondulé',
  '17.21B': 'Fabrication de cartonnages',
  '17.21C': "Fabrication d'emballages en papier",
  '17.22Z': 'Fab. article papier sanit. ou domestique',
  '17.23Z': "Fabrication d'articles de papeterie",
  '17.24Z': 'Fabrication de papiers peints',
  '17.29Z': 'Fab. aut. article en papier ou en carton',
  '18.11Z': 'Imprimerie de journaux',
  '18.12Z': 'Autre imprimerie (labeur)',
  '18.13Z': 'Activités de pré-presse',
  '18.14Z': 'Reliure et activités connexes',
  '18.20Z': "Reproduction d'enregistrements",
  '19.10Z': 'Cokéfaction',
  '19.20Z': 'Raffinage du pétrole',
  '20.11Z': 'Fabrication de gaz industriels',
  '20.12Z': 'Fabrication de colorants et de pigments',
  '20.13A': 'Enrichissment & retrait. mat. nucléaire',
  '20.13B': 'Fab. aut. prod. chim. inorg. base n.c.a.',
  '20.14Z': 'Fab. aut. prod. chimique org. de base',
  '20.15Z': "Fabric. de produits azotés et d'engrais",
  '20.16Z': 'Fabric. de matières plastiques de base',
  '20.17Z': 'Fabrication de caoutchouc synthétique',
  '20.20Z': 'Fab. pesticide & aut. prod. agrochimique',
  '20.30Z': 'Fab. de peinture, vernis, encre & mastic',
  '20.41Z': 'Fab. savon, détergent & prod. entretien',
  '20.42Z': 'Fab. parfum & produit pour la toilette',
  '20.51Z': 'Fabrication de produits explosifs',
  '20.52Z': 'Fabrication de colles',
  '20.53Z': "Fabrication d'huiles essentielles",
  '20.59Z': 'Fabric. autres produits chimiques n.c.a.',
  '20.60Z': 'Fab.  fibre artificielle ou synthétique',
  '21.10Z': 'Fab. de produits pharmaceutiques de base',
  '21.20Z': 'Fabric. de préparations pharmaceutiques',
  '22.11Z': 'Fabrication et rechapage de pneumatiques',
  '22.19Z': "Fabric. d'autres articles en caoutchouc",
  '22.21Z': 'Fab. plaque, feuille, tube,  etc. plast.',
  '22.22Z': "Fab. d'emballage en matière plastique",
  '22.23Z': 'Fab. élément mat. plastiq. pr construct.',
  '22.29A': 'Fab. pièce techniq. base mat. plastiq.',
  '22.29B': 'Fab. prod. conso. courante en plastique',
  '23.11Z': 'Fabrication de verre plat',
  '23.12Z': 'Façonnage & transformation du verre plat',
  '23.13Z': 'Fabrication de verre creux',
  '23.14Z': 'Fabrication de fibres de verre',
  '23.19Z': 'Fab. & façonnage aut. article en verre',
  '23.20Z': 'Fabrication de produits réfractaires',
  '23.31Z': 'Fabrication de carreaux en céramique',
  '23.32Z': 'Fab. produit  construct. en terre cuite',
  '23.41Z': 'Fab. art. céramiq. usage domest. & déco.',
  '23.42Z': 'Fab. appareil sanitaire en céramique',
  '23.43Z': 'Fab. isolateur & pièce isolante céramiq.',
  '23.44Z': 'Fab. aut. prod. céram. à usage technique',
  '23.49Z': "Fabrication d'autres produits céramiques",
  '23.51Z': 'Fabrication de ciment',
  '23.52Z': 'Fabrication de chaux et plâtre',
  '23.61Z': 'Fab. élément en béton pour la construct.',
  '23.62Z': 'Fab. élément en plâtre pour la construc.',
  '23.63Z': "Fabrication de béton prêt à l'emploi",
  '23.64Z': 'Fabrication de mortiers et bétons secs',
  '23.65Z': "Fabrication d'ouvrages en fibre-ciment",
  '23.69Z': 'Fab. aut. ouvrage béton, ciment, plâtre',
  '23.70Z': 'Taille, façonnage & finissage de pierres',
  '23.91Z': 'Fabrication de produits abrasifs',
  '23.99Z': 'Fab. aut. prod. minéraux non métal. nca.',
  '24.10Z': 'Sidérurgie',
  '24.20Z': 'Fab. tube, profilé creux etc. en acier',
  '24.31Z': 'Étirage à froid de barres',
  '24.32Z': 'Laminage à froid de feuillards',
  '24.33Z': 'Profilage à froid par formage ou pliage',
  '24.34Z': 'Tréfilage à froid',
  '24.41Z': 'Production de métaux précieux',
  '24.42Z': "Métallurgie de l'aluminium",
  '24.43Z': 'Métallurgie du Pb, du Zn ou du Sn',
  '24.44Z': 'Métallurgie du cuivre',
  '24.45Z': 'Métallurgie autres métaux non ferreux',
  '24.46Z': 'Élaboration et transform. mat. nucléaire',
  '24.51Z': 'Fonderie de fonte',
  '24.52Z': "Fonderie d'acier",
  '24.53Z': 'Fonderie de métaux légers',
  '24.54Z': "Fonderie d'autres métaux non ferreux",
  '25.11Z': 'Fab. structure métal. & partie structure',
  '25.12Z': 'Fabric. de portes et fenêtres en métal',
  '25.21Z': 'Fab. radiat. & chaudière pr chauf. ctral',
  '25.29Z': 'Fab. aut. réservr, citerne, etc. métal.',
  '25.30Z': 'Fab. générat. vapeur sf pr chauff. ctral',
  '25.40Z': "Fabrication d'armes et de munitions",
  '25.50A': 'Forge; métallurgie des poudres',
  '25.50B': 'Découpage, emboutissage',
  '25.61Z': 'Traitement et revêtement des métaux',
  '25.62A': 'Décolletage',
  '25.62B': 'Mécanique industrielle',
  '25.71Z': 'Fabrication de coutellerie',
  '25.72Z': 'Fabrication de serrures et de ferrures',
  '25.73A': 'Fabrication de moules et modèles',
  '25.73B': "Fabrication d'autres outillages",
  '25.91Z': 'Fab. fût & emballage métalliq. similaire',
  '25.92Z': "Fabric. d'emballages métalliques légers",
  '25.93Z': 'Fab. art.  fil métal., chaîne & ressort',
  '25.94Z': 'Fabrication de vis et de boulons',
  '25.99A': "Fabric. d'articles métalliques ménagers",
  '25.99B': "Fabric. d'autres articles métalliques",
  '26.11Z': 'Fabrication de composants électroniques',
  '26.12Z': 'Fab. de cartes électroniques assemblées',
  '26.20Z': 'Fab. ordinateur & équipement périphériq.',
  '26.30Z': "Fabric. d'équipements de communication",
  '26.40Z': 'Fab. produit électronique grand public',
  '26.51A': "Fab. équipement d'aide à la navigation",
  '26.51B': 'Fab. instrumentation scientifiq. & tech.',
  '26.52Z': 'Horlogerie',
  '26.60Z': 'Fab. éqpt irrad. médic. & électromedic.',
  '26.70Z': 'Fab. matériel optique et photographique',
  '26.80Z': 'Fab. de supports magnétiques et optiques',
  '27.11Z': 'Fab. moteur génér. transfo. & mat. élec.',
  '27.12Z': 'Fab. mat. de distrib. & de cde électri.',
  '27.20Z': 'Fabric. pile & accumulateur électrique',
  '27.31Z': 'Fabrication de câbles de fibres optiques',
  '27.32Z': 'Fab. aut. fil & câble éltron. ou éltriq.',
  '27.33Z': 'Fabric. matériel installation électrique',
  '27.40Z': "Fabric. appareils d'éclairage électrique",
  '27.51Z': "Fabrication d'appareils électroménagers",
  '27.52Z': 'Fab. appareils ménagers non électriques',
  '27.90Z': "Fabric. d'autres matériels électriques",
  '28.11Z': 'Fab. moteur & turb. sf pr avion & véhic.',
  '28.12Z': 'Fab. équipement hydraulique & pneumatiq.',
  '28.13Z': "Fabric. d'autres pompes et compresseurs",
  '28.14Z': 'Fabric. autres articles de robinetterie',
  '28.15Z': 'Fab. engrenage & organe méca. transmis.',
  '28.21Z': 'Fabrication de fours et brûleurs',
  '28.22Z': 'Fab. matériel de levage & de manutention',
  '28.23Z': 'Fab. machine équipt bureau (sf ordinat.)',
  '28.24Z': 'Fab. outillage portatif à moteur incorp.',
  '28.25Z': 'Fab. équipt aérauliq. & frigorifiq. ind.',
  '28.29A': 'Fab. éqpt emballage condition. & pesage',
  '28.29B': "Fab. d'autres machines d'usage général",
  '28.30Z': 'Fab. machines agricoles et forestières',
  '28.41Z': 'Fab. de machines de formage des métaux',
  '28.49Z': "Fabrication d'autres machines-outils",
  '28.91Z': 'Fabric. de machines pour la métallurgie',
  '28.92Z': 'Fab. machine pour extraction ou constr.',
  '28.93Z': "Fab. machine pour l'indus. agro-aliment.",
  '28.94Z': 'Fab. machine pour industries textiles',
  '28.95Z': 'Fab. machine pr indus. papier & carton',
  '28.96Z': 'Fab. machine pr trav. du caoutch, plast.',
  '28.99A': "Fabrication de machines d'imprimerie",
  '28.99B': "Fabric. d'autres machines spécialisées",
  '29.10Z': 'Construction de véhicules automobiles',
  '29.20Z': 'Fabrication de carrosseries et remorques',
  '29.31Z': 'Fab. équipt électriq. & électron. auto.',
  '29.32Z': "Fabric. d'autres équipements automobiles",
  '30.11Z': 'Construct. navires & structure flottante',
  '30.12Z': 'Construction de bateaux de plaisance',
  '30.20Z': 'Const. loco. & autre mat. ferro. roulant',
  '30.30Z': 'Construction aéronautique et spatiale',
  '30.40Z': 'Constr. véhicules militaires de combat',
  '30.91Z': 'Fabrication de motocycles',
  '30.92Z': 'Fab. bicyclette & véhic. pour invalides',
  '30.99Z': 'Fab. aut. équipement de transport n.c.a.',
  '31.01Z': 'Fab. de meubles de bureau et de magasin',
  '31.02Z': 'Fabrication de meubles de cuisine',
  '31.03Z': 'Fabrication de matelas',
  '31.09A': "Fabric. sièges d'ameublement d'intérieur",
  '31.09B': 'Fab. aut. meub. & ind. connexe ameublmnt',
  '32.11Z': 'Frappe de monnaie',
  '32.12Z': 'Fab. article de joaillerie et bijouterie',
  '32.13Z': 'Fab. art. bijout. fantaisie & similaire',
  '32.20Z': "Fabrication d'instruments de musique",
  '32.30Z': "Fabrication d'articles de sport",
  '32.40Z': 'Fabrication de jeux et jouets',
  '32.50A': 'Fab. matériel médico-chirurg. & dentaire',
  '32.50B': 'Fabrication de lunettes',
  '32.91Z': 'Fabrication d’articles de brosserie',
  '32.99Z': 'Autres activités manufacturières n.c.a.',
  '33.11Z': "Réparation d'ouvrages en métaux",
  '33.12Z': 'Répar. machine & équipement mécaniques',
  '33.13Z': 'Répar. matériel électronique & optique',
  '33.14Z': "Réparation d'équipements électriques",
  '33.15Z': 'Réparation et maintenance navale',
  '33.16Z': 'Répar. & maint. aéronef & eng. spatiaux',
  '33.17Z': "Répar. & maint. d'aut. équipt transport",
  '33.19Z': "Réparation d'autres équipements",
  '33.20A': 'Instal. struct. métal., chaudr. & tuyau.',
  '33.20B': 'Instal. machines & équipement mécanique',
  '33.20C': 'Instal. éqpts ctrle des processus indus.',
  '33.20D': 'Inst. éqpt élec. électro. optiq. ou aut.',
  '35.11Z': "Production d'électricité",
  '35.12Z': "Transport d'électricité",
  '35.13Z': "Distribution d'électricité",
  '35.14Z': "Commerce d'électricité",
  '35.21Z': 'Production de combustibles gazeux',
  '35.22Z': 'Distrib. combustible gazeux pr conduites',
  '35.23Z': 'Commerce combustible gazeux par conduite',
  '35.30Z': 'Prod. & distrib. vapeur et air condit.',
  '36.00Z': "Captage, traitement & distribution d'eau",
  '37.00Z': 'Collecte et traitement des eaux usées',
  '38.11Z': 'Collecte des déchets non dangereux',
  '38.12Z': 'Collecte des déchets dangereux',
  '38.21Z': 'Traitmnt & élimin. déchets non dangereux',
  '38.22Z': 'Traitmnt & élimination déchets dangereux',
  '38.31Z': "Démantèlement d'épaves",
  '38.32Z': 'Récupération de déchets triés',
  '39.00Z': 'Dépollution & autre sces gestion déchets',
  '41.10A': 'Promotion immobilière de logements',
  '41.10B': 'Promotion immobilière de bureaux',
  '41.10C': "Promotion immobilière d'autres bâtiments",
  '41.10D': 'Supports juridiques de programmes',
  '41.20A': 'Construction de maisons individuelles',
  '41.20B': "Construction d'autres bâtiments",
  '42.11Z': 'Construction de routes et autoroutes',
  '42.12Z': 'Const. voie ferrée surface & souterraine',
  '42.13A': "Construction d'ouvrages d'art",
  '42.13B': 'Construction et entretien de tunnels',
  '42.21Z': 'Construction de réseaux pour fluides',
  '42.22Z': 'Const. réseaux électriq. & de télécom.',
  '42.91Z': 'Construc. ouvrages maritimes et fluviaux',
  '42.99Z': 'Constr. aut. ouvrage de génie civil nca.',
  '43.11Z': 'Travaux de démolition',
  '43.12A': 'Travaux de terrassement courants',
  '43.12B': 'Travaux de terrassement spécialisés',
  '43.13Z': 'Forages et sondages',
  '43.21A': 'Travaux instal. électriq. ds tous locaux',
  '43.21B': 'Travaux instal. électriq. sr voie publi.',
  '43.22A': 'Travaux instal. eau & gaz en tous locaux',
  '43.22B': 'Travaux instal. équipt thermique & clim.',
  '43.29A': "Travaux d'isolation",
  '43.29B': "Autres travaux d'installation n.c.a.",
  '43.31Z': 'Travaux de plâtrerie',
  '43.32A': 'Travaux de menuiserie bois et PVC',
  '43.32B': 'Travaux menuiserie métal. & serrurerie',
  '43.32C': 'Agencement de lieux de vente',
  '43.33Z': 'Travaux revêtement des sols et des murs',
  '43.34Z': 'Travaux de peinture et vitrerie',
  '43.39Z': 'Autres travaux de finition',
  '43.91A': 'Travaux de charpente',
  '43.91B': 'Travaux de couverture par éléments',
  '43.99A': "Travaux d'étanchéification",
  '43.99B': 'Travaux montage de structure métallique',
  '43.99C': 'Trav. maçon. gle & gros oeuvre bâtiment',
  '43.99D': 'Aut. travaux spécialisés de construction',
  '43.99E': 'Location avec opérateur mat. de constr.',
  '45.11Z': 'Comm. de voiture & véhicule auto. léger',
  '45.19Z': "Commerce d'autres véhicules automobiles",
  '45.20A': 'Entretien & répar. véhicule auto. léger',
  '45.20B': 'Entretien & répar. autre véhicule auto.',
  '45.31Z': "Commerce de gros d'équipement automobile",
  '45.32Z': 'Commerce de détail équipement automobile',
  '45.40Z': 'Commerce et réparation de motocycles',
  '46.11Z': 'Interm. du comm. en produits agricoles',
  '46.12A': "Centrales d'achat de carburant",
  '46.12B': 'Aut. ic comb. mét. minér. & prod. chim.',
  '46.13Z': 'Interm. comm. bois & matériaux construc.',
  '46.14Z': 'Int. comm. équipt indus., navire & avion',
  '46.15Z': 'Int. comm. meuble, art. ménage & quinc.',
  '46.16Z': 'Int. comm. textile, habillt & assimil.',
  '46.17A': "Centrales d'achat alimentaires",
  '46.17B': 'Autre ic en denrées, boissons et tabac',
  '46.18Z': 'Int. spécialis. comm. aut. prod. spécif.',
  '46.19A': "Centrales d'achat non alimentaires",
  '46.19B': 'Autre interm. commerce en prodts divers',
  '46.21Z': 'Com gros céréal. tab. brt & alim. bétail',
  '46.22Z': 'Commerce de gros de fleurs et plantes',
  '46.23Z': "Commerce de gros d'animaux vivants",
  '46.24Z': 'Commerce de gros de cuirs et peaux',
  '46.31Z': 'Commerce de gros de fruits et légumes',
  '46.32A': 'Commerce de gros de viandes de boucherie',
  '46.32B': 'Comm. gros de produits à base de viande',
  '46.32C': 'Commerce de gros de volailles et gibier',
  '46.33Z': 'Com. gros prod. laitier oeuf & mat. grse',
  '46.34Z': 'Commerce de gros  de boissons',
  '46.35Z': 'Comm. gros de produits à base de tabac',
  '46.36Z': 'Com. gros de sucre chocolat & confiserie',
  '46.37Z': 'Comm. gros de café, thé, cacao et épices',
  '46.38A': 'Com. gros aut. alim. yc poisson crustacé',
  '46.38B': 'Comm. gros alimentaire spécialisé divers',
  '46.39A': 'Commerce de gros de produits surgelés',
  '46.39B': 'Comm de gros alimentaire non spécialisé',
  '46.41Z': 'Commerce de gros de textiles',
  '46.42Z': "Commerce gros d'habillement & chaussures",
  '46.43Z': 'Commerce de gros appareil électroménager',
  '46.44Z': 'Com. gros vaisselle verrerie prod. entr.',
  '46.45Z': 'Com. gros parfumerie & produit de beauté',
  '46.46Z': 'Comm. gros de produits pharmaceutiques',
  '46.47Z': 'Com. gros meuble tapis appareil éclaira.',
  '46.48Z': 'Com. gros artic. horlogerie & bijouterie',
  '46.49Z': "Commerce gros d'autres biens domestiques",
  '46.51Z': 'Comm. gros ordi. éqpt périph. & logiciel',
  '46.52Z': 'Cg éqpt & composant électron. & télécom.',
  '46.61Z': 'Commerce de gros de matériel agricole',
  '46.62Z': 'Commerce de gros de machines-outils',
  '46.63Z': 'Com. gros machine pr extrac., constr. GC',
  '46.64Z': 'Com. gros machine pr ind. text. & habil.',
  '46.65Z': 'Commerce de gros de mobilier de bureau',
  '46.66Z': 'Com. gros autre machine & équipt bureau',
  '46.69A': 'Commerce de gros de matériel électrique',
  '46.69B': 'Com. gros fourniture & équipt ind. div.',
  '46.69C': 'Cg fournit. & équipt div. pr com. & sces',
  '46.71Z': 'Com. gros combustible & produits annexes',
  '46.72Z': 'Commerce de gros de minerais et métaux',
  '46.73A': 'Com. gros bois & matériaux construction',
  '46.73B': 'Cg appareil sanitaire & prod. décoration',
  '46.74A': 'Commerce de gros de quincaillerie',
  '46.74B': 'Cg fourniture pour plomberie & chauffage',
  '46.75Z': 'Commerce de gros de produits chimiques',
  '46.76Z': "Commerce gros d'aut. prod. intermédiaire",
  '46.77Z': 'Commerce de gros de déchets et débris',
  '46.90Z': 'Commerce de gros non spécialisé',
  '47.11A': 'Commerce de détail de produits surgelés',
  '47.11B': "Commerce d'alimentation générale",
  '47.11C': 'Supérettes',
  '47.11D': 'Supermarchés',
  '47.11E': 'Magasins multi-commerces',
  '47.11F': 'Hypermarchés',
  '47.19A': 'Grands magasins',
  '47.19B': 'Autres comm. détail en magasin non spéc.',
  '47.21Z': 'Com. détail fruit & légume en mag. spéc.',
  '47.22Z': 'Com. dét. viande & prdt avec viande (ms)',
  '47.23Z': 'Comm. détail poisson crustacé etc. (ms)',
  '47.24Z': 'Comm. dét. pain pâtiss. & confiser. (ms)',
  '47.25Z': 'Com. détail boisson en magasin spéciali.',
  '47.26Z': 'Comm. dét. produit à base de tabac (ms)',
  '47.29Z': 'Aut. com. détail alim. en mag. spéciali.',
  '47.30Z': 'Comm. détail carburant en mag. spéciali.',
  '47.41Z': 'Com. dét ordi. un. périph. & logicl (ms)',
  '47.42Z': 'Comm. dét. matériel télécom. (ms)',
  '47.43Z': 'Comm. dét. matériels audio/vidéo (ms)',
  '47.51Z': 'Com. dét. textiles en magasin spécialisé',
  '47.52A': 'Com. dét. quinc. pein. etc. (mag.<400m2)',
  '47.52B': 'Com. dét. quinc. pein. etc. (mag.>400m2)',
  '47.53Z': 'Cd tapis moquette & revêt. mur sol (ms)',
  '47.54Z': 'Comm. dét.  appareil électroménager (ms)',
  '47.59A': 'Commerce de détail de meubles',
  '47.59B': 'Comm. détail autres équipements du foyer',
  '47.61Z': 'Comm. dét. livres en magasin spécialisé',
  '47.62Z': 'Comm. détail journaux & papeterie (ms)',
  '47.63Z': 'Com. dét. enreg. musicaux & vidéo (ms)',
  '47.64Z': 'Com. dét. articles de sport en mag. spé.',
  '47.65Z': 'Com. dét. jeux & jouets en mag. spécial.',
  '47.71Z': 'Com. dét. habillement en mag. spécialisé',
  '47.72A': 'Commerce de détail de la chaussure',
  '47.72B': 'Com. dét. maroquinerie & article  voyage',
  '47.73Z': 'Comm. dét. produits pharmaceutiques (ms)',
  '47.74Z': 'Com. dét. art. médicaux & orthopéd. (ms)',
  '47.75Z': 'Com. dét. parfumerie & prodt beauté (ms)',
  '47.76Z': 'Com. dét. fleur plante anim. cie + alim.',
  '47.77Z': 'Com. dét. art. horlogerie & bijout. (ms)',
  '47.78A': "Commerces de détail d'optique",
  '47.78B': 'Comm. détail de charbons & combustibles',
  '47.78C': 'Autre commerce détail spécialisé divers',
  '47.79Z': "Comm. détail biens d'occasion en magasin",
  '47.81Z': 'Cd alimentaire sur éventaire & marché',
  '47.82Z': 'Cd textiles habillt & chauss. s/marchés',
  '47.89Z': 'Aut. com. dét. sur éventaires & marchés',
  '47.91A': 'Vente à distance sur catalogue général',
  '47.91B': 'Vente à distance sur catalogue spécialis',
  '47.99A': 'Vente à domicile',
  '47.99B': 'Vente par automate, aut. cd hors magasin',
  '49.10Z': 'Transport ferrov. interurbain voyageur',
  '49.20Z': 'Transports ferroviaires de fret',
  '49.31Z': 'Transport urbain & suburbain de voyageur',
  '49.32Z': 'Transports de voyageurs par taxis',
  '49.39A': 'Transport routier régulier de voyageurs',
  '49.39B': 'Autres transports routiers de voyageurs',
  '49.39C': 'Téléphériques et remontées mécaniques',
  '49.41A': 'Transports routiers de fret interurbains',
  '49.41B': 'Transports routiers de fret de proximité',
  '49.41C': 'Location de camions avec chauffeur',
  '49.42Z': 'Services de déménagement',
  '49.50Z': 'Transports par conduites',
  '50.10Z': 'Transport maritime & côtier de passagers',
  '50.20Z': 'Transports maritimes et côtiers de fret',
  '50.30Z': 'Transports fluviaux de passagers',
  '50.40Z': 'Transports fluviaux de fret',
  '51.10Z': 'Transports aériens de passagers',
  '51.21Z': 'Transports aériens de fret',
  '51.22Z': 'Transports spatiaux',
  '52.10A': 'Entreposage et stockage frigorifique',
  '52.10B': 'Entreposage et stockage non frigorifique',
  '52.21Z': 'Sces auxiliaires de transport terrestre',
  '52.22Z': 'Sces auxiliaires des transports par eau',
  '52.23Z': 'Sces auxiliaires des transports aériens',
  '52.24A': 'Manutention portuaire',
  '52.24B': 'Manutention non portuaire',
  '52.29A': 'Messagerie, fret express',
  '52.29B': 'Affrètement & organisation des transp.',
  '53.10Z': 'Activ. poste (obligation sce universel)',
  '53.20Z': 'Autres activités de poste et de courrier',
  '55.10Z': 'Hôtels et hébergement similaire',
  '55.20Z': 'Hébergt tourist. & aut. hbt courte durée',
  '55.30Z': 'Terrain camping & parc pr caravane etc.',
  '55.90Z': 'Autres hébergements',
  '56.10A': 'Restauration traditionnelle',
  '56.10B': 'Cafétérias et autres libres-services',
  '56.10C': 'Restauration de type rapide',
  '56.21Z': 'Services des traiteurs',
  '56.29A': 'Restauration collective sous contrat',
  '56.29B': 'Autres services de restauration n.c.a.',
  '56.30Z': 'Débits de boissons',
  '58.11Z': 'Édition de livres',
  '58.12Z': "Édition répertoires & fichiers d'adresse",
  '58.13Z': 'Édition de journaux',
  '58.14Z': 'Édition de revues et périodiques',
  '58.19Z': "Autres activités d'édition",
  '58.21Z': 'Édition de jeux électroniques',
  '58.29A': 'Édition de logiciel système et de réseau',
  '58.29B': 'Edit. logiciel outil dévelop. & langage',
  '58.29C': 'Edition de logiciels applicatifs',
  '59.11A': 'Prod. film & progm. pour la télévision',
  '59.11B': 'Prod. film institutionnel & publicitaire',
  '59.11C': 'Production de films pour le cinéma',
  '59.12Z': 'Post-production film & prog. télévision',
  '59.13A': 'Distribution de films cinématographiques',
  '59.13B': 'Edition et distribution vidéo',
  '59.14Z': 'Projection de films cinématographiques',
  '59.20Z': 'Enregistrement sonore & édition musicale',
  '60.10Z': 'Édition et diffusion de programmes radio',
  '60.20A': 'Edition de chaînes généralistes',
  '60.20B': 'Edition de chaînes thématiques',
  '61.10Z': 'Télécommunications filaires',
  '61.20Z': 'Télécommunications sans fil',
  '61.30Z': 'Télécommunications par satellite',
  '61.90Z': 'Autres activités de télécommunication',
  '62.01Z': 'Programmation informatique',
  '62.02A': 'Conseil en système & logiciel informati.',
  '62.02B': 'Tierce mainten. syst. & appli. nformati.',
  '62.03Z': "Gestion d'installations informatiques",
  '62.09Z': 'Autres activités informatiques',
  '63.11Z': 'Traitt donnée, hébergt & activ. connexe',
  '63.12Z': 'Portails Internet',
  '63.91Z': 'Activités des agences de presse',
  '63.99Z': "Autres services d'information n.c.a.",
  '64.11Z': 'Activités de banque centrale',
  '64.19Z': 'Autres intermédiations monétaires',
  '64.20Z': 'Activités des sociétés holding',
  '64.30Z': 'Fonds placement & entité financ. simil.',
  '64.91Z': 'Crédit-bail',
  '64.92Z': 'Autre distribution de crédit',
  '64.99Z': 'Aut. act. finan. hs as. & c. retra. nca.',
  '65.11Z': 'Assurance vie',
  '65.12Z': 'Autres assurances',
  '65.20Z': 'Réassurance',
  '65.30Z': 'Caisses de retraite',
  '66.11Z': 'Administration de marchés financiers',
  '66.12Z': 'Courtage valeur mobilière & marchandise',
  '66.19A': 'Support juridiq. gest. patrimoine mobil.',
  '66.19B': 'Aut. aux. sce financ. hs ass. retr. nca.',
  '66.21Z': 'Évaluation des risques et dommages',
  '66.22Z': "Act. des agents & courtiers d'assurances",
  '66.29Z': 'Aut. act. aux. assur. & caisse retraite',
  '66.30Z': 'Gestion de fonds',
  '68.10Z': 'Activité marchands de biens immobiliers',
  '68.20A': 'Location de logements',
  '68.20B': 'Location terrain & autre bien immobilier',
  '68.31Z': 'Agences immobilières',
  '68.32A': 'Administrat. immeuble & autre bien immo.',
  '68.32B': 'Support juridi. gestion patrimoine immo.',
  '69.10Z': 'Activités juridiques',
  '69.20Z': 'Activités comptables',
  '70.10Z': 'Activités des sièges sociaux',
  '70.21Z': 'Conseil en relation publique & communic.',
  '70.22Z': 'Conseil pr affaire & aut. cons. gestion',
  '71.11Z': "Activités d'architecture",
  '71.12A': 'Activité des géomètres',
  '71.12B': 'Ingénierie, études techniques',
  '71.20A': 'Contrôle technique automobile',
  '71.20B': 'Analyses, essais & inspection technique',
  '72.11Z': 'Recherche-développemnt en biotechnologie',
  '72.19Z': 'R&D : aut. sciences physique & naturelle',
  '72.20Z': 'R&D en sciences humaines et sociales',
  '73.11Z': 'Activités des agences de publicité',
  '73.12Z': 'Régie publicitaire de médias',
  '73.20Z': 'Études de marché et sondages',
  '74.10Z': 'Activités spécialisées de design',
  '74.20Z': 'Activités photographiques',
  '74.30Z': 'Traduction et interprétation',
  '74.90A': 'Activ des économistes de la construction',
  '74.90B': 'Act. spéc. scientif. & techniq. diverses',
  '75.00Z': 'Activités vétérinaires',
  '77.11A': 'Loc. courte durée voit. & v. auto. léger',
  '77.11B': 'Loc. longue durée voit. & v. auto. léger',
  '77.12Z': 'Location et location-bail de camions',
  '77.21Z': 'Loc. & loc.-bail article loisir & sport',
  '77.22Z': 'Location de vidéocassette & disque vidéo',
  '77.29Z': 'Loc. & loc.-bail aut. bien perso. & dom.',
  '77.31Z': 'Loc. & loc.-bail machine & éqpt agricole',
  '77.32Z': 'Loc. & loc.-bail mach. & éqpt pr constr.',
  '77.33Z': 'Loc. & loc.-bail mach. bur. & mat. info.',
  '77.34Z': 'Loc. & loc.-bail mat. transport par eau',
  '77.35Z': 'Loc. & loc.-bail mat. transport aérien',
  '77.39Z': 'Loc. & loc.-bail mach., éqpt & bien div.',
  '77.40Z': 'Loc-bail propr. intel., sf oeuvre avec ©',
  '78.10Z': "Activ. agence placement de main-d'oeuvre",
  '78.20Z': 'Activ. des agences de travail temporaire',
  '78.30Z': 'Aut. mise à dispo. de ressource humaine',
  '79.11Z': 'Activités des agences de voyage',
  '79.12Z': 'Activités des voyagistes',
  '79.90Z': 'Autre serv. réservation & activ. connexe',
  '80.10Z': 'Activités de sécurité privée',
  '80.20Z': 'Activités liées aux systèmes de sécurité',
  '80.30Z': "Activités d'enquête",
  '81.10Z': 'Act. combinée soutien lié aux bâtiments',
  '81.21Z': 'Nettoyage courant des bâtiments',
  '81.22Z': 'Aut. act. nettoyage bâtim. & nett. ind.',
  '81.29A': 'Désinfection désinsectisatn dératisation',
  '81.29B': 'Autres activités de nettoyage n.c.a.',
  '81.30Z': "Services d'aménagement paysager",
  '82.11Z': 'Services admin. combinés de bureau',
  '82.19Z': 'Photocopie & aut. act. spé. sout. bureau',
  '82.20Z': "Activités de centres d'appels",
  '82.30Z': 'Organisation salon profession. & congrès',
  '82.91Z': 'Act. recouv. fac. & info. fin. s/client.',
  '82.92Z': 'Activités de conditionnement',
  '82.99Z': 'Autre activité de soutien aux entr. nca.',
  '84.11Z': 'Administration publique générale',
  '84.12Z': 'A. p. santé form. cult. & soc. (sf sécu)',
  '84.13Z': 'Adm. publique des activités économiques',
  '84.21Z': 'Affaires étrangères',
  '84.22Z': 'Défense',
  '84.23Z': 'Justice',
  '84.24Z': 'Activités d’ordre public et de sécurité',
  '84.25Z': 'Services du feu et de secours',
  '84.30A': 'Activités générales de sécurité sociale',
  '84.30B': 'Gestion des retraites complémentaires',
  '84.30C': 'Distribution sociale de revenus',
  '85.10Z': 'Enseignement pré-primaire',
  '85.20Z': 'Enseignement primaire',
  '85.31Z': 'Enseignement secondaire général',
  '85.32Z': 'Enseignemt secondaire techn. ou profess.',
  '85.41Z': 'Enseignement post-secondaire non sup.',
  '85.42Z': 'Enseignement supérieur',
  '85.51Z': 'Enseigmnt discipl. sport. & act. loisir.',
  '85.52Z': 'Enseignement culturel',
  '85.53Z': 'Enseignement de la conduite',
  '85.59A': "Formation continue d'adultes",
  '85.59B': 'Autres enseignements',
  '85.60Z': "Activités de soutien à l'enseignement",
  '86.10Z': 'Activités hospitalières',
  '86.21Z': 'Activité des médecins généralistes',
  '86.22A': 'Act. radiodiagnostic et de radiothérapie',
  '86.22B': 'Activités chirurgicales',
  '86.22C': 'Autre activité des médecins spécialistes',
  '86.23Z': 'Pratique dentaire',
  '86.90A': 'Ambulances',
  '86.90B': "Laboratoires d'analyses médicales",
  '86.90C': "Centres de collecte et banques d'organes",
  '86.90D': 'Act. des infirmiers et des sages-femmes',
  '86.90E': 'Act. rééduc. appareillag. & pédic.-podo.',
  '86.90F': 'Activités de santé humaine nca.',
  '87.10A': 'Hébergt médicalisé pour personnes âgées',
  '87.10B': 'Hébergt médicalisé pr enfants handicapés',
  '87.10C': 'Hébrgt médic. adul. hand. & aut. ht méd.',
  '87.20A': 'Hébrgt soc. hand. mental & malade mental',
  '87.20B': 'Hébergement social pour toxicomanes',
  '87.30A': 'Hébergement social pour personnes âgées',
  '87.30B': 'Hébergt social pour handicapés physiques',
  '87.90A': 'Hébergt social pr enfants en difficultés',
  '87.90B': 'Hébgt soc. adult., famille en difficulté',
  '88.10A': 'Aide à domicile',
  '88.10B': 'Accueil ss hbgt adult. hand., pers. âgée',
  '88.10C': 'Aide par le travail',
  '88.91A': 'Accueil de jeunes enfants',
  '88.91B': "Accueil sans hébergt d'enfant handicap",
  '88.99A': 'Aut. accueil sans hébrgt enfants & ado.',
  '88.99B': 'Action sociale sans hébergement n.c.a.',
  '90.01Z': 'Arts du spectacle vivant',
  '90.02Z': 'Activités de soutien au spectacle vivant',
  '90.03A': 'Création artistique (arts plastiques)',
  '90.03B': 'Autre création artistique',
  '90.04Z': 'Gestion de salles de spectacles',
  '91.01Z': 'Gestion des bibliothèques & des archives',
  '91.02Z': 'Gestion des musées',
  '91.03Z': 'Gestion site histor. & attraction simil.',
  '91.04Z': 'Gest. jardin bota. & zoo. & réserv. nat.',
  '92.00Z': "Organisation jeux de hasard & d'argent",
  '93.11Z': "Gestion d'installations sportives",
  '93.12Z': 'Activités de clubs de sports',
  '93.13Z': 'Activité des centres de culture physique',
  '93.19Z': 'Autres activités liées au sport',
  '93.21Z': 'Act. parcs attractions & parcs à thèmes',
  '93.29Z': 'Autres activités récréative & de loisirs',
  '94.11Z': 'Act. organisations patronale & consul.',
  '94.12Z': 'Act. des organisations professionnelles',
  '94.20Z': 'Activités des syndicats de salariés',
  '94.91Z': 'Activités des organisations religieuses',
  '94.92Z': 'Activités des organisations politiques',
  '94.99Z': 'Aut. org. fonctionnant par adhé. volont.',
  '95.11Z': 'Répar. ordinateur & équipt périphérique',
  '95.12Z': 'Réparation équipements de communication',
  '95.21Z': 'Réparation prdts électroniq. grd public',
  '95.22Z': 'Répar. électromén. & éqpt maison & jard.',
  '95.23Z': 'Réparation chaussures & articles en cuir',
  '95.24Z': "Réparation meubles & d'équipt du foyer",
  '95.25Z': 'Répar.articles horlogerie & bijouterie',
  '95.29Z': 'Répar. aut. biens personnel & domestique',
  '96.01A': 'Blanchisserie-teinturerie de gros',
  '96.01B': 'Blanchisserie-teinturerie de détail',
  '96.02A': 'Coiffure',
  '96.02B': 'Soins de beauté',
  '96.03Z': 'Services funéraires',
  '96.04Z': 'Entretien corporel',
  '96.09Z': 'Autres services personnels n.c.a.',
  '97.00Z': 'Act. ménage: empl. de person. domestique',
  '98.10Z': 'Act. ménage : prod. biens (usage propre)',
  '98.20Z': 'Act. ménage : prod. serv. (usage propre)',
  '99.00Z': 'Act. organisations extraterritoriales',
}
