name: Run all checks and tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - run: yarn install --immutable
      - run: yarn lint
      - run: yarn checkformat
      - run: yarn test
      - run: yarn build
